import fs from 'fs';
import path from 'path';

const app = process.argv[2];

function postBuildHtaccess(app) {
  const directory = `./dist/${app}/`;

  if (!fs.existsSync(directory)) {
    fs.mkdirSync(directory);
  }

  const content = `# Generated by BlueprintCMS

Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]`;

  const fileName = `.htaccess`;
  const filePath = path.join(directory, fileName);

  fs.writeFileSync(filePath, content);

  console.log(`File ${fileName} successfully created at ${filePath}`);
}


if (!app) {
  console.error('Error: app is required!');
  process.exit(1);
}

postBuildHtaccess(app);
