export const API_MODEL = {
  // TODO #environment-prefix
  posts: 'https://jsonplaceholder.typicode.com/posts',
  postsDetail: 'https://jsonplaceholder.typicode.com/posts/',
  users: 'https://jsonplaceholder.typicode.com/todos',
  usersDetail: 'https://jsonplaceholder.typicode.com/todos/',
  files: 'https://jsonplaceholder.typicode.com/photos',
  filesDetail: 'https://jsonplaceholder.typicode.com/photos/',
  members: 'https://jsonplaceholder.typicode.com/todos',
  membersDetail: 'https://jsonplaceholder.typicode.com/todos/',
  pages: 'https://jsonplaceholder.typicode.com/todos',
  pagesDetail: 'https://jsonplaceholder.typicode.com/todos/',
  translations: 'https://jsonplaceholder.typicode.com/todos',
  translationsDetail: 'https://jsonplaceholder.typicode.com/todos/',
  categories: 'https://jsonplaceholder.typicode.com/todos',
  categoriesDetail: 'https://jsonplaceholder.typicode.com/todos/',
  tags: 'https://jsonplaceholder.typicode.com/todos',
  tagsDetail: 'https://jsonplaceholder.typicode.com/todos/',
  messages: 'https://jsonplaceholder.typicode.com/todos',
  messagesDetail: 'https://jsonplaceholder.typicode.com/todos/',
  menus: 'https://jsonplaceholder.typicode.com/todos',
  menusDetail: 'https://jsonplaceholder.typicode.com/todos/',
  menusItems: 'https://jsonplaceholder.typicode.com/todos',
  menusItemsDetail: 'https://jsonplaceholder.typicode.com/todos/',
};
